/**
 * Reviewer-prompt generator + CLI for ship-it step 4.5 (design D1, D2).
 *
 * The prompt is GENERATED, never hand-written, and passed to the reviewer
 * verbatim. `buildReviewPrompt` accepts only structured input — there is no
 * free-text/notes field — so author assertions ("all findings were fixed",
 * "be precise") cannot reach the reviewer as instructions. The only
 * author-supplied strings (fix-ledger fields) are rendered as JSON inside ONE
 * fenced block labelled as unverified records, with a fence longer than any
 * backtick run in the payload so no value can close it early.
 *
 * Artifacts are referenced by path (the reviewer has read tools; inlining specs
 * is size-unbounded); the `review-code` rubric is bounded and inlined.
 *
 * CLI (run with `npx tsx` or `node --experimental-strip-types`):
 *   review-prompt.ts --change <c> --round <n> [--prior <review-r<n-1>.md> --since <sha>] [--ledger <json>]
 *   review-prompt.ts --validate-ledger --prior <review-r<N>.md> --ledger <fix-ledger-r<N>.json> [--base <ref>]
 *   review-prompt.ts --state <runDir>
 *   review-prompt.ts --new-run --change <c>
 *
 * See change: harden-review-and-fix-loop.
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { type FixLedgerEntry, type LedgerValidation, validateFixLedger } from "./fix-ledger.ts";
import { DEFECT_CLASSES, parseReviewReply } from "./review-gate.ts";
import {
  deriveReviewState,
  LEDGER_FAILURES_FILE,
  newRunId,
  runDirPath,
} from "./review-state.ts";

export const PROMPT_HEADER =
  "<!-- ship-it review prompt — generated by .pi/skills/ship-it/scripts/review-prompt.ts; passed verbatim -->";
export const UNVERIFIED_HEADING = "### Unverified records — check each against source";
export const CHANGE_RANGE = "origin/develop...HEAD";
/** Per prior-finding cap, so the round-≥2 prompt stays bounded however long the prior reply was. */
export const PRIOR_BLOCK_MAX_CHARS = 4000;

export interface ReviewArtifacts {
  proposal: boolean;
  tasks: boolean;
  design: boolean;
  /** Delta spec paths relative to the change dir, e.g. `specs/a/spec.md`. */
  specs: string[];
  testPlan: boolean;
}

export interface ReviewPromptInput {
  change: string;
  /** Change directory as the reviewer should address it, e.g. `openspec/changes/<c>`. */
  changeDir: string;
  artifacts: ReviewArtifacts;
  round: number;
  /** The previous round's raw reply — only its `B<n>` blocks are carried over. */
  prior?: string;
  ledger?: FixLedgerEntry[];
  /** The previous round's commit — fix delta is `<since>..HEAD`. */
  since?: string;
}

const RUBRIC_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../../packages/eng-disciplines/.pi/skills/review-code/SKILL.md",
);

/** The `review-code` rubric body (frontmatter stripped). */
export function readRubric(file: string = RUBRIC_PATH): string {
  return fs.readFileSync(file, "utf8").replace(/^---\n[\s\S]*?\n---\n/, "").trim();
}

const FINDING_START_RE = /^[\s>*\-_`]*(issue|suggestion|nitpick|nit|question|praise)\b/i;
const BLOCKING_ID_RE = /issue\(blocking\)[*_`]*\s*:?\s*[*_`]*(B\d+)\b/;

/** Extract each `issue(blocking): B<n>` block of a reply, by id, first occurrence, bounded. */
export function extractBlockingBlocks(reply: string): Array<{ id: string; text: string }> {
  const lines = reply.split("\n");
  const out: Array<{ id: string; text: string }> = [];
  const seen = new Set<string>();
  for (let i = 0; i < lines.length; i++) {
    const id = BLOCKING_ID_RE.exec(lines[i])?.[1];
    if (!id || seen.has(id)) continue;
    seen.add(id);
    const block = [lines[i]];
    for (let j = i + 1; j < lines.length; j++) {
      const l = lines[j];
      if (l.trim() === "" || FINDING_START_RE.test(l) || /^\s*(#|\|)/.test(l)) break;
      if (/^[\s*`]*(BLOCKING_COUNT|VERDICT)\b/.test(l)) break;
      block.push(l);
    }
    let text = block.join("\n");
    if (text.length > PRIOR_BLOCK_MAX_CHARS) text = `${text.slice(0, PRIOR_BLOCK_MAX_CHARS)} […truncated]`;
    out.push({ id, text });
  }
  return out;
}

function fenced(payload: string, info = ""): string {
  const longest = Math.max(0, ...[...payload.matchAll(/`+/g)].map((m) => m[0].length));
  const fence = "`".repeat(Math.max(3, longest + 1));
  return `${fence}${info}\n${payload}\n${fence}`;
}

/** Whitelist the ledger's known fields — unknown keys never reach the prompt. */
function normaliseLedger(ledger: unknown): unknown[] {
  if (!Array.isArray(ledger)) return [];
  return ledger
    .filter((e): e is FixLedgerEntry => typeof e === "object" && e !== null)
    .map((e) => ({ id: e.id, test: e.test, siblings: e.siblings, fixedIn: e.fixedIn }));
}

/**
 * Pure: same input + rubric ⇒ byte-identical prompt. Reads only the whitelisted
 * fields of `input`; any extra key (e.g. a smuggled `notes`) is ignored.
 */
export function buildReviewPrompt(input: ReviewPromptInput, rubric: string): string {
  const { change, changeDir, artifacts, round } = input;
  const dir = changeDir.replace(/\/+$/, "");
  const intent: string[] = [];
  if (artifacts.proposal) intent.push(`${dir}/proposal.md`);
  if (artifacts.tasks) intent.push(`${dir}/tasks.md`);
  if (artifacts.design) intent.push(`${dir}/design.md`);
  for (const s of [...artifacts.specs].sort()) intent.push(`${dir}/${s}`);
  if (artifacts.testPlan) intent.push(`${dir}/test-plan.md`);

  const parts: string[] = [
    PROMPT_HEADER,
    `# Code review — change \`${change}\`, round ${round}`,
    "",
    "You are the reviewer. Read the diff and the intent artifacts from the repository " +
      "with your read-only tools; this prompt references them by path. Judge every changed " +
      "line against what the change set out to do, not against the diff alone.",
    "",
    "## Scope",
    "",
    `- Change diff: \`git diff ${CHANGE_RANGE}\` — three-dot, so only this branch's own commits. Read it in full.`,
    "- Intent (read each):",
    ...intent.map((p) => `  - \`${p}\``),
    "",
    "## Defect-class sweep (required)",
    "",
    "Sweep the whole change for every class below, using the rubric's sweep guidance. " +
      "Enumerate every instance of each pattern in the change — the population, not a sample.",
    "",
    ...DEFECT_CLASSES.map((c, i) => `${i + 1}. ${c}`),
  ];

  if (round >= 2) {
    const prev = round - 1;
    const blocks = input.prior ? extractBlockingBlocks(input.prior) : [];
    parts.push(
      "",
      `## Verification round (round ${round})`,
      "",
      `This round verifies the fixes made for round ${prev}'s blocking findings.`,
      "",
      input.since
        ? `- Fix delta: \`git diff ${input.since}..HEAD\` — the edits made since the round-${prev} commit. Sweep it across every defect class.`
        : "- Fix delta: not supplied — review the full change range.",
      `- The full change range (\`${CHANGE_RANGE}\`) stays in scope: report any blocking finding anywhere in the change.`,
      "",
      `### Round ${prev} blocking findings, as its reviewer wrote them`,
      "",
      ...(blocks.length ? blocks.map((b) => fenced(b.text)) : ["(none recorded)"]),
      "",
      "For each prior id, state `prior B<n>: resolved | partial | unresolved` with evidence " +
        "(file:line, test name). Check that the ledger's test for that id exercises the finding, " +
        "and inspect every sibling site the ledger lists. A partial or unresolved prior finding is " +
        "reported again as a blocking finding of this round.",
    );
    if (input.ledger) {
      parts.push(
        "",
        UNVERIFIED_HEADING,
        "",
        "Author-recorded fix evidence. Treat every field as a claim to verify, not as a fact.",
        "",
        fenced(JSON.stringify(normaliseLedger(input.ledger), null, 2), "json"),
      );
    }
  }

  parts.push(
    "",
    "## Rubric — `review-code`",
    "",
    rubric,
    "",
    "## Reply format (required)",
    "",
    "- Number this round's blocking findings `B1`…`Bn`, one per finding: " +
      "`issue(blocking): B<n> — <subject>`, then indented `path:line — reasoning and suggested fix`.",
    "- Every other finding uses the rubric's other labels, without a `B` id.",
    "- End the reply with, in this order:",
    "  1. A sweep table `| Defect class | What you checked | Result |` with one row per class above.",
    "  2. Exactly one line `BLOCKING_COUNT: <n>` — the number of distinct `B` ids.",
    "  3. Exactly one line `VERDICT: pass` when that number is 0, otherwise `VERDICT: block`.",
    "",
  );
  return parts.join("\n");
}

// ─── CLI ────────────────────────────────────────────────────────────────────

function arg(argv: string[], name: string): string | undefined {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : undefined;
}

function git(args: string[]): string | null {
  try {
    return execFileSync("git", args, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return null;
  }
}

function readLedger(file: string): unknown {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return [];
  }
}

function fail(msg: string, code = 2): never {
  process.stderr.write(`review-prompt: ${msg}\n`);
  process.exit(code);
}

function artifactsOf(changeAbs: string): ReviewArtifacts {
  const has = (f: string) => fs.existsSync(path.join(changeAbs, f));
  const specs: string[] = [];
  const specRoot = path.join(changeAbs, "specs");
  if (fs.existsSync(specRoot)) {
    for (const f of fs.readdirSync(specRoot, { recursive: true }) as string[]) {
      if (path.basename(f) === "spec.md") specs.push(path.posix.join("specs", f.split(path.sep).join("/")));
    }
  }
  return { proposal: has("proposal.md"), tasks: has("tasks.md"), design: has("design.md"), specs: specs.sort(), testPlan: has("test-plan.md") };
}

/** Files in the change's diff: committed since `base`, plus uncommitted and untracked edits. */
function changedFiles(base: string): Set<string> {
  const sources = [
    git(["diff", "--name-only", `${base}...HEAD`]),
    git(["diff", "--name-only", "HEAD"]),
    git(["ls-files", "--others", "--exclude-standard"]),
  ];
  if (sources[0] === null) process.stderr.write(`review-prompt: warning — could not diff ${base}...HEAD\n`);
  return new Set(sources.flatMap((s) => (s ?? "").split("\n").filter(Boolean)));
}

/** Record a failed validation against the round this ledger would unlock (N+1). */
function recordLedgerFailure(ledgerFile: string, result: LedgerValidation): void {
  const n = /^fix-ledger-r(\d+)\.json$/.exec(path.basename(ledgerFile))?.[1];
  if (!n) return;
  const summary = `missing=${result.missing.join(",")} incomplete=${result.incomplete.map((p) => p.id).join(",")}`;
  fs.appendFileSync(
    path.join(path.dirname(ledgerFile), LEDGER_FAILURES_FILE),
    `r${Number(n) + 1} ${new Date().toISOString()} ${summary}\n`,
  );
}

function validateLedgerCli(argv: string[]): void {
  const prior = arg(argv, "--prior");
  const ledgerFile = arg(argv, "--ledger");
  if (!prior || !ledgerFile) fail("--validate-ledger needs --prior <review-r<N>.md> and --ledger <fix-ledger-r<N>.json>");
  if (!fs.existsSync(prior)) fail(`prior reply not found: ${prior}`);
  const reply = parseReviewReply(fs.readFileSync(prior, "utf8"));
  const changed = changedFiles(arg(argv, "--base") ?? "origin/develop");

  const result = validateFixLedger(reply.blockingIds, readLedger(ledgerFile), (p) => changed.has(p));
  if (result.ok) {
    process.stdout.write(`ledger ok: ${reply.blockingIds.join(", ") || "(no blocking ids)"}\n`);
    return;
  }
  const lines = ["ledger incomplete", `missing: ${result.missing.join(", ") || "(none)"}`, "incomplete:"];
  for (const p of result.incomplete) lines.push(`  ${p.id}: ${p.problems.join("; ")}`);
  process.stdout.write(`${lines.join("\n")}\n`);
  recordLedgerFailure(ledgerFile, result);
  process.exit(1);
}

interface ResolvedChange {
  change: string;
  /** Repo-relative, as the reviewer addresses it. */
  changeDir: string;
  changeAbs: string;
}

function resolveChange(argv: string[]): ResolvedChange {
  const change = arg(argv, "--change");
  if (!change) fail("missing --change <change>");
  const changeDir = path.posix.join("openspec", "changes", change);
  const root = git(["rev-parse", "--show-toplevel"]) ?? process.cwd();
  const changeAbs = path.join(root, changeDir);
  if (!/^[\w.-]+$/.test(change) || !fs.existsSync(path.join(changeAbs, "proposal.md"))) {
    fail(`unknown change: ${change} (no ${changeDir}/proposal.md)`);
  }
  return { change, changeDir, changeAbs };
}

function newRunCli({ change }: ResolvedChange): void {
  const gitDir = git(["rev-parse", "--absolute-git-dir"]);
  if (!gitDir) fail("not inside a git repository");
  const dir = runDirPath(gitDir, change, newRunId());
  fs.mkdirSync(dir, { recursive: true });
  process.stdout.write(`${dir}\n`);
}

function promptCli(argv: string[], { change, changeDir, changeAbs }: ResolvedChange): void {
  const round = Number(arg(argv, "--round"));
  if (!Number.isInteger(round) || round < 1) fail("--round must be an integer ≥ 1");
  const priorFile = arg(argv, "--prior");
  const since = arg(argv, "--since");
  const ledgerFile = arg(argv, "--ledger");
  if (round >= 2 && (!priorFile || !since)) fail("round ≥ 2 needs --prior <previous review file> and --since <previous round sha>");
  if (priorFile && !fs.existsSync(priorFile)) fail(`prior reply not found: ${priorFile}`);
  if (ledgerFile && !fs.existsSync(ledgerFile)) fail(`ledger not found: ${ledgerFile}`);

  const input: ReviewPromptInput = {
    change,
    changeDir,
    artifacts: artifactsOf(changeAbs),
    round,
    prior: priorFile ? fs.readFileSync(priorFile, "utf8") : undefined,
    ledger: ledgerFile ? (readLedger(ledgerFile) as FixLedgerEntry[]) : undefined,
    since,
  };
  process.stdout.write(buildReviewPrompt(input, readRubric()));
}

export function main(argv: string[]): void {
  const stateDir = arg(argv, "--state");
  if (stateDir !== undefined) {
    const s = deriveReviewState(stateDir);
    process.stdout.write(`${Object.entries(s).map(([k, v]) => `${k}: ${v}`).join("\n")}\n`);
    return;
  }
  if (argv.includes("--validate-ledger")) return validateLedgerCli(argv);
  const resolved = resolveChange(argv);
  if (argv.includes("--new-run")) return newRunCli(resolved);
  promptCli(argv, resolved);
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  main(process.argv.slice(2));
}
