/**
 * Repo-level plugin-registry hash parity — folds test-plan scenario E4.
 *
 * The build-time hash and the server-side hash must be computed over the same
 * plugin set. This is the regression guard for the never-converging
 * `PluginStalenessBanner`: a client-less plugin (`mcp-server` shape) used to be
 * counted only by the runtime side.
 *
 * The committed `packages/client/src/generated/plugin-registry.tsx` is a build
 * artifact regenerated by several entry points under DIFFERENT fixture policies
 * — `npm run build` uses production (`excluded`), while the `prelint`/`prebuild`
 * generator runs with `NODE_ENV` unset (`included`, so `demo-plugin` is in the
 * set). The test therefore determines which policy the file on disk was
 * generated under and asserts that BOTH sides agree with it, instead of pinning
 * one policy against an ambient artifact (which is green locally after a
 * production build and red in CI after a dev regeneration).
 *
 * See change: add-served-build-coherence-and-hash-parity (design D0).
 */
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  clearDiscoveryCache,
  discoverPlugins,
  findMonorepoRoot,
  pluginRegistryHash,
} from "../loader.js";
import { bundleRootsFor, selectClientRegistryPlugins } from "../client-registry-set.js";

const repoRoot = findMonorepoRoot();
if (!repoRoot) throw new Error("monorepo root not found from dashboard-plugin-runtime");

function embeddedRegistryHash(): string {
  const file = path.join(repoRoot!, "packages/client/src/generated/plugin-registry.tsx");
  const src = fs.readFileSync(file, "utf-8");
  const match = src.match(/PLUGIN_REGISTRY_HASH\s*=\s*"([0-9a-f]{64})"/);
  if (!match) throw new Error("embedded PLUGIN_REGISTRY_HASH not found");
  return match[1];
}

/** Hash of the shared selector's result over `discovered`, under `isProd`. */
function selectedHash(
  discovered: ReturnType<typeof discoverPlugins>,
  isProd: boolean,
): string {
  return pluginRegistryHash(
    selectClientRegistryPlugins(discovered, { isProd, bundleRoots: bundleRootsFor(repoRoot!) }),
  );
}

describe("plugin-registry hash parity (E4)", () => {
  it("build-side and runtime-side both equal the embedded PLUGIN_REGISTRY_HASH", () => {
    clearDiscoveryCache();
    const buildDiscovered = discoverPlugins(repoRoot!);
    const buildProd = selectedHash(buildDiscovered, true);
    const buildDev = selectedHash(buildDiscovered, false);
    expect(buildDiscovered.length).toBeGreaterThan(0);

    // The server's discovery (no explicit root) must select the same sets.
    clearDiscoveryCache();
    const runtimeDiscovered = discoverPlugins();
    const runtimeProd = selectedHash(runtimeDiscovered, true);
    const runtimeDev = selectedHash(runtimeDiscovered, false);

    // Both sides agree with each other under each policy — the actual fix.
    expect(runtimeProd).toBe(buildProd);
    expect(runtimeDev).toBe(buildDev);

    // And the artifact on disk was generated under one of the two policies; both
    // of its sides must equal it. A hash from neither means the generated
    // registry is stale or was produced over a different set than the selector.
    const embedded = embeddedRegistryHash();
    if (embedded === buildProd) {
      expect(runtimeProd).toBe(embedded);
    } else if (embedded === buildDev) {
      expect(runtimeDev).toBe(embedded);
    } else {
      throw new Error(
        `embedded PLUGIN_REGISTRY_HASH ${embedded} matches neither the shared selector's ` +
          `production set (${buildProd}) nor its dev set (${buildDev})`,
      );
    }
  });

  it("the old runtime basis (no client-entry filter) diverged — the bug this closes", () => {
    clearDiscoveryCache();
    const discovered = discoverPlugins(repoRoot!);
    // Premise of the fix: this checkout has a client-less plugin (`mcp-server`
    // shape). If it ever gains a client entry, the divergence goes away and
    // this characterization test should be retired with it.
    expect(discovered.filter((p) => !p.clientEntryPath).length).toBeGreaterThan(0);
    const legacyRuntimeBasis = discovered.filter((p) => p.manifest.fixture !== true);
    expect(pluginRegistryHash(legacyRuntimeBasis)).not.toBe(embeddedRegistryHash());
  });
});
