/**
 * Generate the LLM's IR knob reference (`reference/ir-fields.md`) from the
 * schema's own `description`/`type`/`default` keywords — one source of truth,
 * so the field reference can never drift from what `validate` enforces.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { pkgRoot } from "../util/paths.js";

export interface SchemaNode {
  $ref?: string;
  type?: string;
  description?: string;
  default?: unknown;
  enum?: unknown[];
  properties?: Record<string, SchemaNode>;
  items?: SchemaNode;
  additionalProperties?: SchemaNode | boolean;
}

export interface FieldRow {
  path: string;
  type: string;
  default: string;
  description: string;
}

export function loadSchema(): { properties: Record<string, SchemaNode>; definitions: Record<string, SchemaNode> } {
  const path = join(pkgRoot(), "src", "ir", "schema.json");
  return JSON.parse(readFileSync(path, "utf8")) as {
    properties: Record<string, SchemaNode>;
    definitions: Record<string, SchemaNode>;
  };
}

function resolve(node: SchemaNode, defs: Record<string, SchemaNode>): SchemaNode {
  if (node.$ref) {
    const name = node.$ref.replace("#/definitions/", "");
    return { ...defs[name], ...node, $ref: undefined };
  }
  return node;
}

function typeLabel(node: SchemaNode): string {
  if (node.enum) return node.enum.map((v) => String(v)).join(" | ");
  if (node.type === "array") return "array";
  return node.type ?? "any";
}

function defaultLabel(node: SchemaNode): string {
  if (node.default === undefined) return "";
  return `\`${JSON.stringify(node.default)}\``;
}

function escapeCell(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
}

/** Every named property + dynamic-key segment in the schema, pre-order. */
export function collectFieldPaths(schema = loadSchema()): FieldRow[] {
  const defs = schema.definitions;
  const rows: FieldRow[] = [];
  const visitObject = (n: SchemaNode, path: string): void => {
    for (const [key, child] of Object.entries(n.properties ?? {})) visit(child, path ? `${path}.${key}` : key);
    if (n.additionalProperties && typeof n.additionalProperties === "object") {
      visit(n.additionalProperties, `${path}["<key>"]`);
    }
  };
  const visit = (node: SchemaNode, path: string): void => {
    const n = resolve(node, defs);
    rows.push({ path, type: typeLabel(n), default: defaultLabel(n), description: n.description ?? "" });
    if (n.type === "object") visitObject(n, path);
    else if (n.type === "array" && n.items) visit(n.items, `${path}[]`);
  };
  for (const [key, child] of Object.entries(schema.properties)) visit(child, key);
  return rows;
}

export function renderIrFieldsMd(schema = loadSchema()): string {
  const rows = collectFieldPaths(schema);
  const lines = [
    "# Deck IR field reference",
    "",
    "> Generated from `src/ir/schema.json` by `scripts/gen-ir-fields.ts` (`npm run build`). Do not edit by hand.",
    "",
    "`defaults` and `slides[]` are **derived** — regenerated by `parse`; edit them and the change is lost on re-parse. `overrides` is the only region you may write.",
    "",
    "| Path | Type | Default | Effect |",
    "|------|------|---------|--------|",
  ];
  for (const row of rows) {
    lines.push(`| \`${row.path}\` | ${escapeCell(row.type)} | ${row.default} | ${escapeCell(row.description)} |`);
  }
  lines.push("");
  return lines.join("\n");
}
